//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xuat_Chieu
    {
        public Xuat_Chieu()
        {
            this.Chi_Tiet_Lich_Chieu = new HashSet<Chi_Tiet_Lich_Chieu>();
        }
    
        public int IdXuatChieu { get; set; }
        public Nullable<System.DateTime> GioBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianChieu { get; set; }
    
        public virtual ICollection<Chi_Tiet_Lich_Chieu> Chi_Tiet_Lich_Chieu { get; set; }
    }
}
